### ISSUE TITLE
Missing instructions in README.md

### ISSUE THREAD

**Issue by shyam-king** [SelvaKarthik17/transfinitte-22#9]
When you hit the API, we get a 500 error with the following error log:
```
ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/backend/app.py", line 20, in generateFamilyTree
    res = engine_of_program(name, age, state, voter_id, gender, relation_name)
  File "/app/backend/engine/engine.py", line 28, in engine_of_program
    data = get_ind_gov_details(user_data, captcha_path)
  File "/app/backend/indgov_search.py", line 42, in get_ind_gov_details
    captcha = solve_captcha(captcha_path).strip()
  File "/app/backend/captcha_solver.py", line 21, in solve_captcha
    docai_client = documentai.DocumentProcessorServiceClient(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/documentai_v1/services/document_processor_service/client.py", line 502, in __init__
    self._transport = Transport(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/documentai_v1/services/document_processor_service/transports/grpc.py", line 157, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/documentai_v1/services/document_processor_service/transports/base.py", line 106, in __init__
    credentials, _ = google.auth.default(
  File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 583, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 576, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 225, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 119, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File key.json was not found.
127.0.0.1 - - [19/Oct/2022 10:23:00] "POST / HTTP/1.1" 500 -
```

**Comment by haribaz** [comment]
![image](https://user-images.githubusercontent.com/63287231/196670899-226cd5a1-0721-4067-a121-766975aad425.png)
To run the server locally, two keys are essential.
The keys are in the **GCP keys** folder in the drive folder for which the link was attached in the google form we submitted.
@shyam-king
